id: I44595869
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:52:36+00:00'
last_modified: '2022-06-08T05:41:10.553128+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6688
  title: 'རྫ་ཙིག་གཏམ་རྒྱུད།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A344:
      image_group_id: I3CN6690
      title: ''
      total_pages: 33
      order: 1
      base_file: A344.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
